version: "3.1"
language: "mn"   
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 60
- name: EntitySynonymMapper

policies:
- name: RulePolicy
assistant_id: 20260115-094236-another-angler
